"""TS-03 casework foundation

Revision ID: 0001_ts03
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_ts03"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "elder_case",
        sa.Column("upstream_enrollment_ref", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_actor_id", sa.String(length=200), nullable=False),
        sa.Column("created_by_actor_type", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "created_by_actor_type IN ('HUMAN', 'SYSTEM', 'AI', 'AUTOMATION')",
            name="ck_case_actor_type",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "idempotency_record",
        sa.Column("actor_id", sa.String(length=200), nullable=False),
        sa.Column("operation", sa.String(length=100), nullable=False),
        sa.Column("target", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("actor_id", "operation", "target", "key", name="uq_idempotency_scope"),
    )
    op.create_table(
        "audit_entry",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.String(length=200), nullable=False),
        sa.Column("actor_type", sa.String(length=20), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("correlation_id", sa.String(length=200), nullable=False),
        sa.Column("before_reference", sa.Uuid(), nullable=True),
        sa.Column("after_reference", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "actor_type IN ('HUMAN', 'SYSTEM', 'AI', 'AUTOMATION')", name="ck_audit_actor_type"
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["elder_case.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_entry_case_id"), "audit_entry", ["case_id"], unique=False)
    op.create_index(
        "ix_audit_timeline", "audit_entry", ["case_id", "timestamp", "id"], unique=False
    )
    op.create_table(
        "case_assignment",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("caregiver_actor_id", sa.String(length=200), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("assigned_by_actor_id", sa.String(length=200), nullable=False),
        sa.Column("assigned_by_actor_type", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "assigned_by_actor_type IN ('HUMAN', 'SYSTEM', 'AI', 'AUTOMATION')",
            name="ck_assignment_actor_type",
        ),
        sa.CheckConstraint("ended_at IS NULL OR ended_at >= started_at", name="ck_assignment_time"),
        sa.CheckConstraint("length(trim(reason)) > 0", name="ck_assignment_reason"),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["elder_case.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_case_assignment_case_id"), "case_assignment", ["case_id"], unique=False
    )
    op.create_index(
        "uq_assignment_active",
        "case_assignment",
        ["case_id"],
        unique=True,
        postgresql_where=sa.text("ended_at IS NULL"),
    )
    op.create_table(
        "case_interaction",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("interaction_type", sa.String(length=20), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("supersedes_interaction_id", sa.Uuid(), nullable=True),
        sa.Column("correction_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_by_actor_id", sa.String(length=200), nullable=False),
        sa.Column("recorded_by_actor_type", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "interaction_type IN ('CONTACT', 'MONITORING')", name="ck_interaction_type"
        ),
        sa.CheckConstraint(
            "recorded_by_actor_type IN ('HUMAN', 'SYSTEM', 'AI', 'AUTOMATION')",
            name="ck_interaction_actor_type",
        ),
        sa.CheckConstraint(
            "(supersedes_interaction_id IS NULL AND correction_reason IS NULL) OR "
            "(supersedes_interaction_id IS NOT NULL AND correction_reason IS NOT "
            "NULL AND length(trim(correction_reason)) > 0)",
            name="ck_interaction_correction",
        ),
        sa.ForeignKeyConstraint(
            ["case_id", "supersedes_interaction_id"],
            ["case_interaction.case_id", "case_interaction.id"],
            name="fk_interaction_lineage",
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["elder_case.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "id", name="uq_interaction_case_id"),
        sa.UniqueConstraint("supersedes_interaction_id", name="uq_interaction_successor"),
    )
    op.create_index(
        op.f("ix_case_interaction_case_id"), "case_interaction", ["case_id"], unique=False
    )
    op.create_table(
        "case_observation",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("record_type", sa.String(length=20), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("supersedes_observation_id", sa.Uuid(), nullable=True),
        sa.Column("correction_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_by_actor_id", sa.String(length=200), nullable=False),
        sa.Column("recorded_by_actor_type", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "record_type IN ('OBSERVATION', 'NEED_CAPTURE')", name="ck_observation_type"
        ),
        sa.CheckConstraint(
            "recorded_by_actor_type IN ('HUMAN', 'SYSTEM', 'AI', 'AUTOMATION')",
            name="ck_observation_actor_type",
        ),
        sa.CheckConstraint(
            "(supersedes_observation_id IS NULL AND correction_reason IS NULL) OR "
            "(supersedes_observation_id IS NOT NULL AND correction_reason IS NOT "
            "NULL AND length(trim(correction_reason)) > 0)",
            name="ck_observation_correction",
        ),
        sa.ForeignKeyConstraint(
            ["case_id", "supersedes_observation_id"],
            ["case_observation.case_id", "case_observation.id"],
            name="fk_observation_lineage",
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["elder_case.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "id", name="uq_observation_case_id"),
        sa.UniqueConstraint("supersedes_observation_id", name="uq_observation_successor"),
    )
    op.create_index(
        op.f("ix_case_observation_case_id"), "case_observation", ["case_id"], unique=False
    )
    op.create_table(
        "case_profile_revision",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("elder_reference", sa.Text(), nullable=False),
        sa.Column("supersedes_revision_id", sa.Uuid(), nullable=True),
        sa.Column("correction_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_by_actor_id", sa.String(length=200), nullable=False),
        sa.Column("recorded_by_actor_type", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "recorded_by_actor_type IN ('HUMAN', 'SYSTEM', 'AI', 'AUTOMATION')",
            name="ck_profile_actor_type",
        ),
        sa.CheckConstraint(
            "(revision_no = 1 AND supersedes_revision_id IS NULL AND "
            "correction_reason IS NULL) OR (revision_no > 1 AND "
            "supersedes_revision_id IS NOT NULL AND correction_reason IS NOT NULL "
            "AND length(trim(correction_reason)) > 0)",
            name="ck_profile_correction",
        ),
        sa.CheckConstraint("revision_no > 0", name="ck_profile_revision_positive"),
        sa.ForeignKeyConstraint(
            ["case_id", "supersedes_revision_id"],
            ["case_profile_revision.case_id", "case_profile_revision.id"],
            name="fk_profile_lineage",
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["elder_case.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "id", name="uq_profile_case_id"),
        sa.UniqueConstraint("case_id", "revision_no", name="uq_profile_revision"),
        sa.UniqueConstraint("supersedes_revision_id", name="uq_profile_successor"),
    )
    op.create_index(
        op.f("ix_case_profile_revision_case_id"), "case_profile_revision", ["case_id"], unique=False
    )
    op.create_table(
        "contact_point_revision",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("logical_contact_id", sa.Uuid(), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("contact_kind", sa.String(length=100), nullable=False),
        sa.Column("contact_value", sa.Text(), nullable=False),
        sa.Column("supersedes_revision_id", sa.Uuid(), nullable=True),
        sa.Column("correction_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_by_actor_id", sa.String(length=200), nullable=False),
        sa.Column("recorded_by_actor_type", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "recorded_by_actor_type IN ('HUMAN', 'SYSTEM', 'AI', 'AUTOMATION')",
            name="ck_contact_actor_type",
        ),
        sa.CheckConstraint(
            "(revision_no = 1 AND supersedes_revision_id IS NULL AND "
            "correction_reason IS NULL) OR (revision_no > 1 AND "
            "supersedes_revision_id IS NOT NULL AND correction_reason IS NOT NULL "
            "AND length(trim(correction_reason)) > 0)",
            name="ck_contact_correction",
        ),
        sa.CheckConstraint("revision_no > 0", name="ck_contact_revision_positive"),
        sa.ForeignKeyConstraint(
            ["case_id", "logical_contact_id", "supersedes_revision_id"],
            [
                "contact_point_revision.case_id",
                "contact_point_revision.logical_contact_id",
                "contact_point_revision.id",
            ],
            name="fk_contact_lineage",
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["elder_case.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "case_id", "logical_contact_id", "id", name="uq_contact_lineage_target"
        ),
        sa.UniqueConstraint(
            "case_id", "logical_contact_id", "revision_no", name="uq_contact_revision"
        ),
        sa.UniqueConstraint("supersedes_revision_id", name="uq_contact_successor"),
    )
    op.create_index(
        op.f("ix_contact_point_revision_case_id"),
        "contact_point_revision",
        ["case_id"],
        unique=False,
    )
    op.create_table(
        "outbox_event",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["elder_case.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_outbox_event_case_id"), "outbox_event", ["case_id"], unique=False)
    # ### end Alembic commands ###

    # Immutable history is protected even if an application role is accidentally over-granted.
    op.execute("""
        CREATE FUNCTION nasim_reject_history_change() RETURNS trigger
        LANGUAGE plpgsql AS $$ BEGIN
            RAISE EXCEPTION 'TS-03 history is append-only' USING ERRCODE = '42501';
        END $$
    """)
    for table in (
        "elder_case",
        "case_profile_revision",
        "contact_point_revision",
        "case_interaction",
        "case_observation",
        "audit_entry",
        "idempotency_record",
    ):
        op.execute(
            f"CREATE TRIGGER protect_history BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION nasim_reject_history_change()"
        )
    op.execute("""
        CREATE FUNCTION nasim_assignment_end_only() RETURNS trigger
        LANGUAGE plpgsql AS $$ BEGIN
            IF TG_OP = 'DELETE' THEN
                RAISE EXCEPTION 'Assignment history cannot be deleted' USING ERRCODE = '42501';
            END IF;
            IF OLD.ended_at IS NOT NULL OR NEW.ended_at IS NULL
               OR (to_jsonb(OLD) - 'ended_at') IS DISTINCT FROM (to_jsonb(NEW) - 'ended_at') THEN
                RAISE EXCEPTION 'Only ending an active assignment is allowed'
                    USING ERRCODE = '42501';
            END IF;
            RETURN NEW;
        END $$
    """)
    op.execute(
        "CREATE TRIGGER protect_assignment BEFORE UPDATE OR DELETE ON case_assignment "
        "FOR EACH ROW EXECUTE FUNCTION nasim_assignment_end_only()"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_outbox_event_case_id"), table_name="outbox_event")
    op.drop_table("outbox_event")
    op.drop_index(op.f("ix_contact_point_revision_case_id"), table_name="contact_point_revision")
    op.drop_table("contact_point_revision")
    op.drop_index(op.f("ix_case_profile_revision_case_id"), table_name="case_profile_revision")
    op.drop_table("case_profile_revision")
    op.drop_index(op.f("ix_case_observation_case_id"), table_name="case_observation")
    op.drop_table("case_observation")
    op.drop_index(op.f("ix_case_interaction_case_id"), table_name="case_interaction")
    op.drop_table("case_interaction")
    op.drop_index(
        "uq_assignment_active",
        table_name="case_assignment",
        postgresql_where=sa.text("ended_at IS NULL"),
    )
    op.drop_index(op.f("ix_case_assignment_case_id"), table_name="case_assignment")
    op.drop_table("case_assignment")
    op.drop_index("ix_audit_timeline", table_name="audit_entry")
    op.drop_index(op.f("ix_audit_entry_case_id"), table_name="audit_entry")
    op.drop_table("audit_entry")
    op.drop_table("idempotency_record")
    op.drop_table("elder_case")
    # ### end Alembic commands ###

    op.execute("DROP FUNCTION nasim_assignment_end_only()")
    op.execute("DROP FUNCTION nasim_reject_history_change()")
