"""TS-05 authorization foundation

Revision ID: 0002_ts05
Revises: 0001_ts03
"""

from collections.abc import Sequence
from uuid import NAMESPACE_URL, uuid5

import sqlalchemy as sa
from alembic import op

revision: str = "0002_ts05"
down_revision: str | Sequence[str] | None = "0001_ts03"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authorization_audit",
        sa.Column("actor_id", sa.String(length=200), nullable=False),
        sa.Column("actor_type", sa.String(length=20), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("correlation_id", sa.String(length=200), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("before_reference", sa.Uuid(), nullable=True),
        sa.Column("after_reference", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "action IN ('REGISTERED','CREATED','ENDED')", name="ck_authorization_audit_action"
        ),
        sa.CheckConstraint(
            "actor_type IN ('HUMAN','SYSTEM','AI','AUTOMATION')",
            name="ck_authorization_audit_actor",
        ),
        sa.CheckConstraint(
            "length(trim(actor_id)) > 0 AND length(trim(reason)) > 0 AND lengt"
            "h(trim(correlation_id)) > 0",
            name="ck_authorization_audit_provenance",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "resource_type", "resource_id", "action", name="uq_authorization_audit_event"
        ),
    )
    op.create_table(
        "permission_definition",
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_by_actor_id", sa.String(length=200), nullable=False),
        sa.Column("recorded_by_actor_type", sa.String(length=20), nullable=False),
        sa.Column("correlation_id", sa.String(length=200), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "length(trim(code)) > 0 AND position('*' in code) = 0 AND length(trim(title)) > 0",
            name="ck_permission_definition_code",
        ),
        sa.CheckConstraint(
            "recorded_by_actor_type IN ('HUMAN','SYSTEM','AI','AUTOMATION')",
            name="ck_permission_definition_actor",
        ),
        sa.CheckConstraint(
            "(revision_no = 1 AND supersedes_id IS NULL) OR (revision_no > 1 A"
            "ND supersedes_id IS NOT NULL)",
            name="ck_permission_definition_version",
        ),
        sa.CheckConstraint(
            "length(trim(reason)) > 0 AND length(trim(correlation_id)) > 0 AND"
            " length(trim(recorded_by_actor_id)) > 0",
            name="ck_permission_definition_provenance",
        ),
        sa.ForeignKeyConstraint(
            ["code", "supersedes_id"],
            ["permission_definition.code", "permission_definition.id"],
            name="fk_permission_definition_lineage",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", "id", name="uq_permission_definition_lineage"),
        sa.UniqueConstraint("code", "revision_no", name="uq_permission_definition_version"),
        sa.UniqueConstraint("supersedes_id", name="uq_permission_definition_successor"),
    )
    op.create_table(
        "role_definition",
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_by_actor_id", sa.String(length=200), nullable=False),
        sa.Column("recorded_by_actor_type", sa.String(length=20), nullable=False),
        sa.Column("correlation_id", sa.String(length=200), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "length(trim(code)) > 0 AND position('*' in code) = 0 AND length(trim(title)) > 0",
            name="ck_role_definition_code",
        ),
        sa.CheckConstraint(
            "recorded_by_actor_type IN ('HUMAN','SYSTEM','AI','AUTOMATION')",
            name="ck_role_definition_actor",
        ),
        sa.CheckConstraint(
            "(revision_no = 1 AND supersedes_id IS NULL) OR (revision_no > 1 A"
            "ND supersedes_id IS NOT NULL)",
            name="ck_role_definition_version",
        ),
        sa.CheckConstraint(
            "length(trim(reason)) > 0 AND length(trim(correlation_id)) > 0 AND"
            " length(trim(recorded_by_actor_id)) > 0",
            name="ck_role_definition_provenance",
        ),
        sa.ForeignKeyConstraint(
            ["code", "supersedes_id"],
            ["role_definition.code", "role_definition.id"],
            name="fk_role_definition_lineage",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", "id", name="uq_role_definition_lineage"),
        sa.UniqueConstraint("code", "revision_no", name="uq_role_definition_version"),
        sa.UniqueConstraint("supersedes_id", name="uq_role_definition_successor"),
    )
    op.create_table(
        "actor_role_assignment",
        sa.Column("actor_id", sa.String(length=200), nullable=False),
        sa.Column("actor_type", sa.String(length=20), nullable=False),
        sa.Column("role_code", sa.String(length=100), nullable=False),
        sa.Column("role_revision_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_by_actor_id", sa.String(length=200), nullable=True),
        sa.Column("ended_by_actor_type", sa.String(length=20), nullable=True),
        sa.Column("end_reason", sa.Text(), nullable=True),
        sa.Column("end_correlation_id", sa.String(length=200), nullable=True),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_by_actor_id", sa.String(length=200), nullable=False),
        sa.Column("recorded_by_actor_type", sa.String(length=20), nullable=False),
        sa.Column("correlation_id", sa.String(length=200), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "(ended_at IS NULL AND ended_by_actor_id IS NULL AND ended_by_acto"
            "r_type IS NULL AND end_reason IS NULL AND end_correlation_id IS N"
            "ULL) OR (ended_at >= recorded_at AND ended_by_actor_id IS NOT NUL"
            "L AND length(trim(ended_by_actor_id)) > 0 AND ended_by_actor_type"
            " IN ('HUMAN','SYSTEM','AI','AUTOMATION') AND end_reason IS NOT NU"
            "LL AND length(trim(end_reason)) > 0 AND end_correlation_id IS NOT"
            " NULL AND length(trim(end_correlation_id)) > 0)",
            name="ck_actor_role_end",
        ),
        sa.CheckConstraint(
            "actor_type IN ('HUMAN','SYSTEM','AI','AUTOMATION') AND length(trim(actor_id)) > 0",
            name="ck_actor_role_identity",
        ),
        sa.CheckConstraint(
            "recorded_by_actor_type IN ('HUMAN','SYSTEM','AI','AUTOMATION')",
            name="ck_actor_role_actor",
        ),
        sa.CheckConstraint(
            "expires_at IS NULL OR expires_at > starts_at", name="ck_actor_role_window"
        ),
        sa.CheckConstraint(
            "length(trim(reason)) > 0 AND length(trim(correlation_id)) > 0 AND"
            " length(trim(recorded_by_actor_id)) > 0",
            name="ck_actor_role_provenance",
        ),
        sa.ForeignKeyConstraint(
            ["actor_id", "actor_type", "role_code", "supersedes_id"],
            [
                "actor_role_assignment.actor_id",
                "actor_role_assignment.actor_type",
                "actor_role_assignment.role_code",
                "actor_role_assignment.id",
            ],
            name="fk_actor_role_lineage",
        ),
        sa.ForeignKeyConstraint(
            ["role_code", "role_revision_id"],
            ["role_definition.code", "role_definition.id"],
            name="fk_actor_role",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "actor_id", "actor_type", "role_code", "id", name="uq_actor_role_lineage"
        ),
        sa.UniqueConstraint("supersedes_id", name="uq_actor_role_successor"),
    )
    op.create_index(
        "uq_actor_role_active",
        "actor_role_assignment",
        ["actor_id", "actor_type", "role_code"],
        unique=True,
        postgresql_where=sa.text("ended_at IS NULL"),
    )
    op.create_table(
        "role_permission_grant",
        sa.Column("role_code", sa.String(length=100), nullable=False),
        sa.Column("role_revision_id", sa.Uuid(), nullable=False),
        sa.Column("permission_code", sa.String(length=100), nullable=False),
        sa.Column("permission_revision_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_by_actor_id", sa.String(length=200), nullable=True),
        sa.Column("ended_by_actor_type", sa.String(length=20), nullable=True),
        sa.Column("end_reason", sa.Text(), nullable=True),
        sa.Column("end_correlation_id", sa.String(length=200), nullable=True),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_by_actor_id", sa.String(length=200), nullable=False),
        sa.Column("recorded_by_actor_type", sa.String(length=20), nullable=False),
        sa.Column("correlation_id", sa.String(length=200), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "(ended_at IS NULL AND ended_by_actor_id IS NULL AND ended_by_acto"
            "r_type IS NULL AND end_reason IS NULL AND end_correlation_id IS N"
            "ULL) OR (ended_at >= recorded_at AND ended_by_actor_id IS NOT NUL"
            "L AND length(trim(ended_by_actor_id)) > 0 AND ended_by_actor_type"
            " IN ('HUMAN','SYSTEM','AI','AUTOMATION') AND end_reason IS NOT NU"
            "LL AND length(trim(end_reason)) > 0 AND end_correlation_id IS NOT"
            " NULL AND length(trim(end_correlation_id)) > 0)",
            name="ck_grant_end",
        ),
        sa.CheckConstraint(
            "recorded_by_actor_type IN ('HUMAN','SYSTEM','AI','AUTOMATION')", name="ck_grant_actor"
        ),
        sa.CheckConstraint("expires_at IS NULL OR expires_at > starts_at", name="ck_grant_window"),
        sa.CheckConstraint(
            "length(trim(reason)) > 0 AND length(trim(correlation_id)) > 0 AND"
            " length(trim(recorded_by_actor_id)) > 0",
            name="ck_grant_provenance",
        ),
        sa.ForeignKeyConstraint(
            ["permission_code", "permission_revision_id"],
            ["permission_definition.code", "permission_definition.id"],
            name="fk_grant_permission",
        ),
        sa.ForeignKeyConstraint(
            ["role_code", "permission_code", "supersedes_id"],
            [
                "role_permission_grant.role_code",
                "role_permission_grant.permission_code",
                "role_permission_grant.id",
            ],
            name="fk_grant_lineage",
        ),
        sa.ForeignKeyConstraint(
            ["role_code", "role_revision_id"],
            ["role_definition.code", "role_definition.id"],
            name="fk_grant_role",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role_code", "permission_code", "id", name="uq_grant_lineage"),
        sa.UniqueConstraint("supersedes_id", name="uq_grant_successor"),
    )
    op.create_index(
        "uq_grant_active",
        "role_permission_grant",
        ["role_code", "permission_code"],
        unique=True,
        postgresql_where=sa.text("ended_at IS NULL"),
    )
    # ### end Alembic commands ###

    # Immutable registry/audit: one-way ending retains original and adds provenance.
    for table in ("role_definition", "permission_definition", "authorization_audit"):
        op.execute(
            f"CREATE TRIGGER protect_auth_history BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION nasim_reject_history_change()"
        )
    op.execute("""
        CREATE FUNCTION nasim_auth_end_only() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF TG_OP = 'DELETE' THEN
            RAISE EXCEPTION 'Authorization history cannot be deleted' USING ERRCODE='42501';
          END IF;
          IF OLD.ended_at IS NOT NULL OR NEW.ended_at IS NULL OR
             (to_jsonb(OLD) - ARRAY['ended_at','ended_by_actor_id','ended_by_actor_type',
                'end_reason','end_correlation_id']) IS DISTINCT FROM
             (to_jsonb(NEW) - ARRAY['ended_at','ended_by_actor_id','ended_by_actor_type',
                'end_reason','end_correlation_id']) THEN
            RAISE EXCEPTION 'Only ending an active authorization row is allowed'
              USING ERRCODE='42501';
          END IF;
          RETURN NEW;
        END $$
    """)
    for table in ("actor_role_assignment", "role_permission_grant"):
        op.execute(
            f"CREATE TRIGGER protect_auth_history BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION nasim_auth_end_only()"
        )
    op.execute("""
        CREATE FUNCTION nasim_auth_lineage() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE old_row jsonb;
        BEGIN
          IF NEW.supersedes_id IS NOT NULL THEN
            EXECUTE format('SELECT to_jsonb(t) FROM %I t WHERE id=$1', TG_TABLE_NAME)
              INTO old_row USING NEW.supersedes_id;
            IF TG_TABLE_NAME IN ('role_definition','permission_definition') THEN
              IF NEW.revision_no <> (old_row->>'revision_no')::integer + 1 THEN
                RAISE EXCEPTION 'Invalid definition version' USING ERRCODE='23514';
              END IF;
            ELSIF old_row->>'ended_at' IS NULL THEN
              RAISE EXCEPTION 'Predecessor must be explicitly ended' USING ERRCODE='23514';
            END IF;
          END IF;
          RETURN NEW;
        END $$
    """)
    # Deferred until commit: each accepted record/end MUST have matching audit provenance.
    op.execute("""
        CREATE FUNCTION nasim_auth_require_audit() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE item jsonb; event text; event_actor text; event_type text;
                event_time timestamptz; event_reason text; event_correlation text;
        BEGIN
          item := to_jsonb(NEW);
          IF TG_OP = 'UPDATE' THEN
            event := 'ENDED'; event_actor := NEW.ended_by_actor_id;
            event_type := NEW.ended_by_actor_type; event_time := NEW.ended_at;
            event_reason := NEW.end_reason; event_correlation := NEW.end_correlation_id;
          ELSE
            event := CASE WHEN TG_TABLE_NAME IN ('role_definition','permission_definition')
                      THEN 'REGISTERED' ELSE 'CREATED' END;
            event_actor := NEW.recorded_by_actor_id; event_type := NEW.recorded_by_actor_type;
            event_time := NEW.recorded_at; event_reason := NEW.reason;
            event_correlation := NEW.correlation_id;
          END IF;
          IF NOT EXISTS (SELECT 1 FROM authorization_audit a
             WHERE a.resource_type=TG_TABLE_NAME AND a.resource_id=NEW.id
             AND a.action=event AND a.after_reference=NEW.id
             AND a.before_reference IS NOT DISTINCT FROM
               CASE WHEN event='ENDED' THEN NEW.id ELSE (item->>'supersedes_id')::uuid END
             AND a.actor_id=event_actor AND a.actor_type=event_type
             AND a.timestamp=event_time AND a.reason=event_reason
             AND a.correlation_id=event_correlation) THEN
            RAISE EXCEPTION 'Matching authorization audit required' USING ERRCODE='23514';
          END IF;
          RETURN NULL;
        END $$
    """)
    for table in (
        "role_definition",
        "permission_definition",
        "actor_role_assignment",
        "role_permission_grant",
    ):
        op.execute(
            f"CREATE TRIGGER verify_auth_lineage BEFORE INSERT ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION nasim_auth_lineage()"
        )
        op.execute(
            f"CREATE CONSTRAINT TRIGGER require_auth_audit AFTER INSERT OR UPDATE ON {table} "
            "DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION nasim_auth_require_audit()"
        )
    # Frozen source-backed vocabulary only. No RolePermissionGrant or assignments are seeded.
    registry = [
        ("role_definition", "elder", "سالمند", "e27f7127-01a5-5454-964e-ac6f9bdfa775"),
        (
            "role_definition",
            "family",
            "خانواده / همراه سالمند",
            "45ef1a18-80aa-58f6-86e2-0cbed4f435ab",
        ),
        ("role_definition", "caregiver", "سالمندیار", "74af3197-77c7-5946-990f-2301e849f21f"),
        (
            "role_definition",
            "senior_caregiver",
            "سالمندیار ارشد",
            "9149ea4e-8bb8-5b74-997d-1d2e327adaac",
        ),
        (
            "role_definition",
            "neighborhood_supervisor",
            "سرپرست محله",
            "c46956de-a8b7-5e39-abd5-d6c5f3bcf2bc",
        ),
        (
            "role_definition",
            "regional_supervisor",
            "سرپرست منطقه",
            "c188e288-d801-5b1c-a12f-573624d52621",
        ),
        (
            "role_definition",
            "county_network_manager",
            "مدیر شبکه شهرستان",
            "47dea9b3-c7cc-5df1-bcef-41679d24f2a6",
        ),
        (
            "role_definition",
            "province_network_manager",
            "مدیر شبکه استان",
            "425a51ac-38ef-530b-8f42-8b2c2e48c1d1",
        ),
        (
            "role_definition",
            "nasim_operator",
            "شرکت / اپراتور نسیم",
            "3409b5e0-804e-55af-97d6-965c655172f4",
        ),
        ("role_definition", "employer", "کارفرما", "23054419-c3ef-542e-a5a5-061db8d5bebe"),
        (
            "role_definition",
            "specialist_provider",
            "شریک / ارائه\u200cدهنده تخصصی",
            "6cb7a0f4-9e77-5df8-aa83-be045942879f",
        ),
        ("role_definition", "nasim_system", "سامانه نسیم", "31cd2173-df74-5d69-abdb-d1e435a31bec"),
        (
            "role_definition",
            "nasim_ai",
            "هوش مصنوعی داخلی نسیم",
            "2d4096cc-6bd3-521a-b3b8-004dc3953a37",
        ),
        (
            "permission_definition",
            "case.create",
            "case.create",
            "93780be3-937d-598f-83b3-b2093dbf78c5",
        ),
        (
            "permission_definition",
            "case.read.assigned",
            "case.read.assigned",
            "37f91fb3-f144-5f81-abc0-2114d671c975",
        ),
        (
            "permission_definition",
            "case.monitor.assigned",
            "case.monitor.assigned",
            "b18d0abd-ca7f-53ec-b68a-c7bdb4360b45",
        ),
        (
            "permission_definition",
            "case.observe.assigned",
            "case.observe.assigned",
            "4bf18a39-ac58-5d36-bb38-3dbc942d15a2",
        ),
        (
            "permission_definition",
            "case.contact.manage.assigned",
            "case.contact.manage.assigned",
            "f62d57cc-a257-5a73-959e-99ec424916e4",
        ),
        (
            "permission_definition",
            "case.assignment.manage",
            "case.assignment.manage",
            "77aa470e-f661-5e63-a6bf-13465ff505ce",
        ),
        (
            "permission_definition",
            "case.read.oversight",
            "case.read.oversight",
            "ec4e0077-d083-5f32-84e8-d1f875334dac",
        ),
    ]
    connection = op.get_bind()
    for table, code, title, identifier in registry:
        values = dict(id=identifier, code=code, title=title)
        connection.execute(
            sa.text(f"""
          INSERT INTO {table} (id,code,title,revision_no,recorded_at,recorded_by_actor_id,
            recorded_by_actor_type,correlation_id,reason)
          VALUES (:id,:code,:title,1,transaction_timestamp(),'schema-migration','SYSTEM',
            '0002_ts05','Source vocabulary registration only; no authority grant')
        """),
            values,
        )
        connection.execute(
            sa.text("""
          INSERT INTO authorization_audit (id,actor_id,actor_type,timestamp,reason,
            correlation_id,resource_type,resource_id,action,before_reference,after_reference)
          VALUES (:audit_id,'schema-migration','SYSTEM',transaction_timestamp(),
            'Source vocabulary registration only; no authority grant','0002_ts05',:table,
            :id,'REGISTERED',NULL,:id)
        """),
            dict(
                audit_id=str(uuid5(NAMESPACE_URL, "nasim:audit:" + identifier)),
                table=table,
                id=identifier,
            ),
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_grant_active",
        table_name="role_permission_grant",
        postgresql_where=sa.text("ended_at IS NULL"),
    )
    op.drop_table("role_permission_grant")
    op.drop_index(
        "uq_actor_role_active",
        table_name="actor_role_assignment",
        postgresql_where=sa.text("ended_at IS NULL"),
    )
    op.drop_table("actor_role_assignment")
    op.drop_table("role_definition")
    op.drop_table("permission_definition")
    op.drop_table("authorization_audit")
    # ### end Alembic commands ###

    op.execute("DROP FUNCTION nasim_auth_require_audit()")
    op.execute("DROP FUNCTION nasim_auth_lineage()")
    op.execute("DROP FUNCTION nasim_auth_end_only()")
