"""Referral recording foundation

Revision ID: 0003_referral
Revises: 0002_ts05
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003_referral"
down_revision: str | Sequence[str] | None = "0002_ts05"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "referral_record",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("source_need_observation_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_actor_id", sa.String(length=200), nullable=False),
        sa.Column("created_by_actor_type", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("correlation_id", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "created_by_actor_type IN ('HUMAN','SYSTEM','AI','AUTOMATION')",
            name="ck_referral_actor_type",
        ),
        sa.CheckConstraint(
            "reason ~ '[^[:space:]]' AND length(trim(correlation_id)) > 0 "
            "AND length(trim(created_by_actor_id)) > 0",
            name="ck_referral_provenance",
        ),
        sa.ForeignKeyConstraint(
            ["case_id", "source_need_observation_id"],
            ["case_observation.case_id", "case_observation.id"],
            name="fk_referral_same_case_need",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_referral_case_created", "referral_record", ["case_id", "created_at", "id"], unique=False
    )
    # ### end Alembic commands ###

    op.execute(
        "CREATE TRIGGER protect_referral_history BEFORE UPDATE OR DELETE ON referral_record "
        "FOR EACH ROW EXECUTE FUNCTION nasim_reject_history_change()"
    )
    op.execute("""
        CREATE FUNCTION nasim_referral_source_guard() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          -- Shared lock with TS-03 correction/reassignment, including direct SQL inserts.
          PERFORM id FROM elder_case WHERE id=NEW.case_id FOR UPDATE;
          IF NEW.created_by_actor_type = 'AI' THEN
            RAISE EXCEPTION 'AI referral recording is not admitted' USING ERRCODE='42501';
          END IF;
          IF NOT EXISTS (SELECT 1 FROM case_observation o
             WHERE o.id=NEW.source_need_observation_id AND o.case_id=NEW.case_id
             AND o.record_type='NEED_CAPTURE') THEN
            RAISE EXCEPTION 'Same-case NEED_CAPTURE required' USING ERRCODE='23514';
          END IF;
          IF EXISTS (SELECT 1 FROM case_observation
             WHERE supersedes_observation_id=NEW.source_need_observation_id) THEN
            RAISE EXCEPTION 'Superseded source is stale' USING ERRCODE='23514';
          END IF;
          RETURN NEW;
        END $$
    """)
    op.execute(
        "CREATE TRIGGER verify_referral_source BEFORE INSERT ON referral_record "
        "FOR EACH ROW EXECUTE FUNCTION nasim_referral_source_guard()"
    )
    op.execute("""
        CREATE FUNCTION nasim_referral_effects_guard() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF NOT EXISTS (SELECT 1 FROM audit_entry a WHERE a.case_id=NEW.case_id
              AND a.action='referral.recorded.v1' AND a.resource_type='referral_record'
              AND a.resource_id=NEW.id AND a.after_reference=NEW.id
              AND a.before_reference=NEW.source_need_observation_id
              AND a.actor_id=NEW.created_by_actor_id AND a.actor_type=NEW.created_by_actor_type
              AND a.timestamp=NEW.created_at AND a.reason=NEW.reason
              AND a.correlation_id=NEW.correlation_id) OR
             NOT EXISTS (SELECT 1 FROM outbox_event e WHERE e.case_id=NEW.case_id
              AND e.event_type='referral.recorded.v1' AND e.occurred_at=NEW.created_at
              AND e.payload->>'referral_id'=NEW.id::text
              AND e.payload->>'case_id'=NEW.case_id::text
              AND e.payload->>'source_need_observation_id'=NEW.source_need_observation_id::text
              AND e.payload->>'actor_id'=NEW.created_by_actor_id
              AND e.payload->>'actor_type'=NEW.created_by_actor_type
              AND e.payload->>'correlation_id'=NEW.correlation_id) OR
             NOT EXISTS (SELECT 1 FROM idempotency_record i
              WHERE i.actor_id=NEW.created_by_actor_id
              AND i.operation='referral.record.' || NEW.created_by_actor_type
              AND i.target=NEW.case_id::text AND i.created_at=NEW.created_at
              AND i.response->>'id'=NEW.id::text
              AND i.response->>'source_need_observation_id'=
                  NEW.source_need_observation_id::text) THEN
            RAISE EXCEPTION 'Atomic referral effects required' USING ERRCODE='23514';
          END IF;
          RETURN NULL;
        END $$
    """)
    op.execute(
        "CREATE CONSTRAINT TRIGGER require_referral_effects AFTER INSERT ON referral_record "
        "DEFERRABLE INITIALLY DEFERRED FOR EACH ROW "
        "EXECUTE FUNCTION nasim_referral_effects_guard()"
    )
    # Frozen permission vocabulary only; never seed role grants or actor assignments.
    registry = [
        (
            "referral.create.assigned",
            "2b044756-78a6-52bf-b47e-4b67d3bcc389",
            "5df9f32d-1c27-5a22-aa71-1f312227675e",
        ),
        (
            "referral.read.assigned",
            "8eb19e07-2bb3-5fe5-a98c-c96d39f79c6a",
            "9858d523-07c1-53a3-9864-7d872e2eddba",
        ),
        (
            "referral.read.oversight",
            "952fdc9f-5b47-5984-9069-b91dbfbc7a01",
            "3388b127-2bae-5282-a0f2-0b1b4ca1e7b1",
        ),
    ]
    connection = op.get_bind()
    for code, identifier, audit_id in registry:
        connection.execute(
            sa.text("""
          INSERT INTO permission_definition (id,code,title,revision_no,recorded_at,
            recorded_by_actor_id,recorded_by_actor_type,correlation_id,reason)
          VALUES (:id,:code,:code,1,transaction_timestamp(),'schema-migration','SYSTEM',
            '0003_referral','Technical referral vocabulary only; no role mapping')
        """),
            dict(id=identifier, code=code),
        )
        connection.execute(
            sa.text("""
          INSERT INTO authorization_audit (id,actor_id,actor_type,timestamp,reason,
            correlation_id,resource_type,resource_id,action,before_reference,after_reference)
          VALUES (:audit_id,'schema-migration','SYSTEM',transaction_timestamp(),
            'Technical referral vocabulary only; no role mapping','0003_referral',
            'permission_definition',:id,'REGISTERED',NULL,:id)
        """),
            dict(audit_id=audit_id, id=identifier),
        )


def downgrade() -> None:
    # Fail closed if a real authorization history depends on this vocabulary.
    connection = op.get_bind()
    used = connection.scalar(
        sa.text("""
        SELECT EXISTS(SELECT 1 FROM role_permission_grant g
          JOIN permission_definition p ON p.id=g.permission_revision_id
          WHERE p.code LIKE 'referral.%') OR EXISTS(
          SELECT 1 FROM permission_definition WHERE code LIKE 'referral.%' AND revision_no>1)
    """)
    )
    if used:
        raise RuntimeError("Referral authorization history requires an approved rollback data plan")
    # Privileged rollback removes migration seeds only, never grant/assignment history.
    op.execute("ALTER TABLE permission_definition DISABLE TRIGGER protect_auth_history")
    op.execute("ALTER TABLE authorization_audit DISABLE TRIGGER protect_auth_history")
    for _code, identifier, audit_id in [
        (
            "referral.create.assigned",
            "2b044756-78a6-52bf-b47e-4b67d3bcc389",
            "5df9f32d-1c27-5a22-aa71-1f312227675e",
        ),
        (
            "referral.read.assigned",
            "8eb19e07-2bb3-5fe5-a98c-c96d39f79c6a",
            "9858d523-07c1-53a3-9864-7d872e2eddba",
        ),
        (
            "referral.read.oversight",
            "952fdc9f-5b47-5984-9069-b91dbfbc7a01",
            "3388b127-2bae-5282-a0f2-0b1b4ca1e7b1",
        ),
    ]:
        connection.execute(
            sa.text("DELETE FROM authorization_audit WHERE id=:id"), dict(id=audit_id)
        )
        connection.execute(
            sa.text("DELETE FROM permission_definition WHERE id=:id"), dict(id=identifier)
        )
    op.execute("ALTER TABLE permission_definition ENABLE TRIGGER protect_auth_history")
    op.execute("ALTER TABLE authorization_audit ENABLE TRIGGER protect_auth_history")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_referral_case_created", table_name="referral_record")
    op.drop_table("referral_record")
    # ### end Alembic commands ###

    op.execute("DROP FUNCTION nasim_referral_effects_guard()")
    op.execute("DROP FUNCTION nasim_referral_source_guard()")
